# Site settings

title: KISS Audio
description: >-                   # Multiline description below
  Keep It Simple Stupid with the design of Audio components (KISS Audio)
baseurl: "/kiss-audio"            # Subpath of the site
url: "https://plstonge.github.io" # Protocol and base hostname

# Build settings
# theme:
markdown: GFM
# plugins:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
